apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: character-sheet
  labels:
    {{- include "character-sheet.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "character-sheet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database 