# PostgreSQL Service
# This service provides a stable network endpoint for PostgreSQL database
# Services abstract the underlying pods and provide service discovery

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: character-sheet
  labels:
    app: postgres
    component: database
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use Network Load Balancer if external access needed
spec:
  type: ClusterIP  # Internal service only (most secure for database)
  
  # Service ports
  ports:
  - port: 5432        # Service port
    targetPort: 5432  # Container port
    protocol: TCP
    name: postgres
  
  # Select pods with these labels
  selector:
    app: postgres
    component: database

---
# Optional: Headless Service for PostgreSQL
# Useful for stateful applications or direct pod access
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: character-sheet
  labels:
    app: postgres
    component: database
  annotations:
    description: "Headless service for direct pod access"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service
  
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  
  selector:
    app: postgres
    component: database 