# Helm values for External Secrets Operator
# This file configures the External Secrets Operator installation
# Used with: helm install external-secrets external-secrets/external-secrets -f external-secrets-operator-values.yaml

# Image configuration
image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  tag: ""  # Use chart default

# Replica count
replicaCount: 1

# Install CRDs
installCRDs: true

# Resource limits and requests
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# Security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

# Pod security context
podSecurityContext:
  fsGroup: 65534

# Service account
serviceAccount:
  create: true
  name: "external-secrets-controller"
  annotations: {}

# RBAC
rbac:
  create: true

# Webhook configuration
webhook:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

# Metrics
metrics:
  service:
    enabled: true

# Logging
log:
  level: info 